export const KEYS = {
  projects: () => ["projects"] as const,
  project: (id: string) => ["projects", id] as const,
  agents: (projectId: string) => ["projects", projectId, "agents"] as const,
  stories: (projectId: string) => ["projects", projectId, "stories"] as const,
  epics: (projectId: string) => ["projects", projectId, "epics"] as const,
  sprints: (projectId: string) => ["projects", projectId, "sprints"] as const,
  analytics: (projectId: string, metric: string) => ["projects", projectId, "analytics", metric] as const,
  requirements: (projectId: string) => ["projects", projectId, "requirements"] as const,
  workflows: (projectId: string) => ["projects", projectId, "workflows"] as const,
  workflowTemplates: () => ["workflows", "templates"] as const,
  templates: () => ["templates"] as const,
  template: (id: string) => ["templates", id] as const,
  users: () => ["users"] as const,
  settings: () => ["settings"] as const,
  models: () => ["models"] as const,
  modelProviders: () => ["models", "providers"] as const,
};
